// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDryPfRvrMEF4yxX3XRrk40S70xMeFoF84',
    appId: '1:287113966962:web:5e246bfc61d385230619eb',
    messagingSenderId: '287113966962',
    projectId: 'myvideo-faba1',
    authDomain: 'myvideo-faba1.firebaseapp.com',
    storageBucket: 'myvideo-faba1.appspot.com',
    measurementId: 'G-3BBL5KV90J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg7inhl4sHTFZ8n-kASY1mo1983SJkzMg',
    appId: '1:287113966962:android:54e69cc485e264660619eb',
    messagingSenderId: '287113966962',
    projectId: 'myvideo-faba1',
    storageBucket: 'myvideo-faba1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaRgnA7EY7saVa6UzRDXCjVKU8bhw6o3c',
    appId: '1:287113966962:ios:d6cf9b638f6e789e0619eb',
    messagingSenderId: '287113966962',
    projectId: 'myvideo-faba1',
    storageBucket: 'myvideo-faba1.appspot.com',
    iosClientId: '287113966962-578aq9iboq5gpoef3gsvlqmlvtib2unt.apps.googleusercontent.com',
    iosBundleId: 'com.uninterrupted.app.noInterrupt',
  );
}
